### ISSUE TITLE
Memory leak on Annotation

### ISSUE THREAD

**Issue by timsainb** [JARVIS-MoCap/JARVIS-AnnotationTool#13] opened 2022-09-27 20:43 UTC
This is on a machine with 32GB ram on ubuntu 20.04 with a dataset with 1000 frames and 5 cameras. 

With each frame annotated, my ran slowly fills up. After annotating less than 20 frames, the program crashes with full RAM. 

This is the full readout:

```
$ AnnotationTool 
2022-09-27T16:21:50: [W] Initializing RHI with OpenGL backend (unknown - unknown:0)
Killed
```

**Comment by JARVIS-MoCap** [comment] 2022-10-05 14:31
Since you're getting the line `2022-09-27T16:21:50: [W] Initializing RHI with OpenGL backend (unknown - unknown:0)` in the output I'm assuming you opened the 3D viewer window right? 

During testing I noticed that opening and then closing the 3D viewer window causes the RAM to steadily fill up until the process is killed just as you describe it. Just to confirm this is indeed the only issue, does the memory leak also happen when you do not close the 3D viewer window? 

Thanks for your help,
Timo

**Comment by timsainb** [comment] 2022-10-06 17:10
Thanks Timo,

I just tested your hypothesis that it is the 3D viewer and I can confirm that it is. I then updated to the new release (dabd4701-dirty) but the memory leak continues (again, not until after I open the 3D viewer).

**Comment by JARVIS-MoCap** [comment] 2022-10-06 22:10
Thanks for trying it out! Does the memory leak happen as soon as you open the 3D viewer or only after closing it? 
And does the memory fill up only when you add annotations or gradually over time?

**Comment by timsainb** [comment] 2022-10-06 22:29
I only noticed it after I closed it and it fills gradually even if I don’t annotate

**Comment by JARVIS-MoCap** [comment] 2022-10-07 09:35
I just tested the installer that I uploaded on the Releases page on two different Ubuntu 20.04 machines and did not see any memory leaks over time. 
That being said the change that fixed the issue for me was to clear the Qt3D canvas before closing the window. I am not sure why this helps and what causes the memory leak in the first place. Digging into it a bit I found some references on the QT forums that reference similar issues (like [this](https://bugreports.qt.io/browse/QTBUG-61293?attachmentOrder=asc)). One entry I can't seem to find anymore also mentioned issue on specific CPU graphics architectures. 
I'm 90% sure this is some unexpected behavior in Qt3D itself, so I will probably have to give up on troubleshooting this for now. As far as I understand it this is not a critical issue for you, since you can avoid it by not closing the 3D viewer window, right?

**Comment by timsainb** [comment] 2022-10-07 12:28
Yeah, this isn’t a critical issue I can still label my data, and there’s no reason to use the 3D tool when I’m doing so.

**Closed** 2023-03-08 18:55 UTC
